// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Jub_Ethereum.proto

#ifndef PROTOBUF_Jub_5fEthereum_2eproto__INCLUDED
#define PROTOBUF_Jub_5fEthereum_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "Jub_Common.pb.h"
// @@protoc_insertion_point(includes)

namespace protobuf_Jub_5fEthereum_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[3];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsContextCfgETHImpl();
void InitDefaultsContextCfgETH();
void InitDefaultsErc20BuilderImpl();
void InitDefaultsErc20Builder();
void InitDefaultsTransactionETHImpl();
void InitDefaultsTransactionETH();
inline void InitDefaults() {
  InitDefaultsContextCfgETH();
  InitDefaultsErc20Builder();
  InitDefaultsTransactionETH();
}
}  // namespace protobuf_Jub_5fEthereum_2eproto
namespace JUB {
namespace Proto {
namespace Ethereum {
class ContextCfgETH;
class ContextCfgETHDefaultTypeInternal;
extern ContextCfgETHDefaultTypeInternal _ContextCfgETH_default_instance_;
class Erc20Builder;
class Erc20BuilderDefaultTypeInternal;
extern Erc20BuilderDefaultTypeInternal _Erc20Builder_default_instance_;
class TransactionETH;
class TransactionETHDefaultTypeInternal;
extern TransactionETHDefaultTypeInternal _TransactionETH_default_instance_;
}  // namespace Ethereum
}  // namespace Proto
}  // namespace JUB
namespace JUB {
namespace Proto {
namespace Ethereum {

enum ENUM_PUB_FORMAT {
  HEX = 0,
  XPUB = 1,
  ENUM_PUB_FORMAT_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  ENUM_PUB_FORMAT_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool ENUM_PUB_FORMAT_IsValid(int value);
const ENUM_PUB_FORMAT ENUM_PUB_FORMAT_MIN = HEX;
const ENUM_PUB_FORMAT ENUM_PUB_FORMAT_MAX = XPUB;
const int ENUM_PUB_FORMAT_ARRAYSIZE = ENUM_PUB_FORMAT_MAX + 1;

const ::google::protobuf::EnumDescriptor* ENUM_PUB_FORMAT_descriptor();
inline const ::std::string& ENUM_PUB_FORMAT_Name(ENUM_PUB_FORMAT value) {
  return ::google::protobuf::internal::NameOfEnum(
    ENUM_PUB_FORMAT_descriptor(), value);
}
inline bool ENUM_PUB_FORMAT_Parse(
    const ::std::string& name, ENUM_PUB_FORMAT* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ENUM_PUB_FORMAT>(
    ENUM_PUB_FORMAT_descriptor(), name, value);
}
// ===================================================================

class ContextCfgETH : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:JUB.Proto.Ethereum.ContextCfgETH) */ {
 public:
  ContextCfgETH();
  virtual ~ContextCfgETH();

  ContextCfgETH(const ContextCfgETH& from);

  inline ContextCfgETH& operator=(const ContextCfgETH& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ContextCfgETH(ContextCfgETH&& from) noexcept
    : ContextCfgETH() {
    *this = ::std::move(from);
  }

  inline ContextCfgETH& operator=(ContextCfgETH&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ContextCfgETH& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ContextCfgETH* internal_default_instance() {
    return reinterpret_cast<const ContextCfgETH*>(
               &_ContextCfgETH_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(ContextCfgETH* other);
  friend void swap(ContextCfgETH& a, ContextCfgETH& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ContextCfgETH* New() const PROTOBUF_FINAL { return New(NULL); }

  ContextCfgETH* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ContextCfgETH& from);
  void MergeFrom(const ContextCfgETH& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ContextCfgETH* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string main_path = 1;
  void clear_main_path();
  static const int kMainPathFieldNumber = 1;
  const ::std::string& main_path() const;
  void set_main_path(const ::std::string& value);
  #if LANG_CXX11
  void set_main_path(::std::string&& value);
  #endif
  void set_main_path(const char* value);
  void set_main_path(const char* value, size_t size);
  ::std::string* mutable_main_path();
  ::std::string* release_main_path();
  void set_allocated_main_path(::std::string* main_path);

  // uint32 chainID = 2;
  void clear_chainid();
  static const int kChainIDFieldNumber = 2;
  ::google::protobuf::uint32 chainid() const;
  void set_chainid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:JUB.Proto.Ethereum.ContextCfgETH)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr main_path_;
  ::google::protobuf::uint32 chainid_;
  mutable int _cached_size_;
  friend struct ::protobuf_Jub_5fEthereum_2eproto::TableStruct;
  friend void ::protobuf_Jub_5fEthereum_2eproto::InitDefaultsContextCfgETHImpl();
};
// -------------------------------------------------------------------

class Erc20Builder : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:JUB.Proto.Ethereum.Erc20Builder) */ {
 public:
  Erc20Builder();
  virtual ~Erc20Builder();

  Erc20Builder(const Erc20Builder& from);

  inline Erc20Builder& operator=(const Erc20Builder& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Erc20Builder(Erc20Builder&& from) noexcept
    : Erc20Builder() {
    *this = ::std::move(from);
  }

  inline Erc20Builder& operator=(Erc20Builder&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Erc20Builder& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Erc20Builder* internal_default_instance() {
    return reinterpret_cast<const Erc20Builder*>(
               &_Erc20Builder_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(Erc20Builder* other);
  friend void swap(Erc20Builder& a, Erc20Builder& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Erc20Builder* New() const PROTOBUF_FINAL { return New(NULL); }

  Erc20Builder* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Erc20Builder& from);
  void MergeFrom(const Erc20Builder& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Erc20Builder* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string tokenTo = 1;
  void clear_tokento();
  static const int kTokenToFieldNumber = 1;
  const ::std::string& tokento() const;
  void set_tokento(const ::std::string& value);
  #if LANG_CXX11
  void set_tokento(::std::string&& value);
  #endif
  void set_tokento(const char* value);
  void set_tokento(const char* value, size_t size);
  ::std::string* mutable_tokento();
  ::std::string* release_tokento();
  void set_allocated_tokento(::std::string* tokento);

  // string tokenValueInWei = 2;
  void clear_tokenvalueinwei();
  static const int kTokenValueInWeiFieldNumber = 2;
  const ::std::string& tokenvalueinwei() const;
  void set_tokenvalueinwei(const ::std::string& value);
  #if LANG_CXX11
  void set_tokenvalueinwei(::std::string&& value);
  #endif
  void set_tokenvalueinwei(const char* value);
  void set_tokenvalueinwei(const char* value, size_t size);
  ::std::string* mutable_tokenvalueinwei();
  ::std::string* release_tokenvalueinwei();
  void set_allocated_tokenvalueinwei(::std::string* tokenvalueinwei);

  // @@protoc_insertion_point(class_scope:JUB.Proto.Ethereum.Erc20Builder)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr tokento_;
  ::google::protobuf::internal::ArenaStringPtr tokenvalueinwei_;
  mutable int _cached_size_;
  friend struct ::protobuf_Jub_5fEthereum_2eproto::TableStruct;
  friend void ::protobuf_Jub_5fEthereum_2eproto::InitDefaultsErc20BuilderImpl();
};
// -------------------------------------------------------------------

class TransactionETH : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:JUB.Proto.Ethereum.TransactionETH) */ {
 public:
  TransactionETH();
  virtual ~TransactionETH();

  TransactionETH(const TransactionETH& from);

  inline TransactionETH& operator=(const TransactionETH& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TransactionETH(TransactionETH&& from) noexcept
    : TransactionETH() {
    *this = ::std::move(from);
  }

  inline TransactionETH& operator=(TransactionETH&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const TransactionETH& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TransactionETH* internal_default_instance() {
    return reinterpret_cast<const TransactionETH*>(
               &_TransactionETH_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(TransactionETH* other);
  friend void swap(TransactionETH& a, TransactionETH& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TransactionETH* New() const PROTOBUF_FINAL { return New(NULL); }

  TransactionETH* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const TransactionETH& from);
  void MergeFrom(const TransactionETH& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(TransactionETH* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string gasPriceInWei = 4;
  void clear_gaspriceinwei();
  static const int kGasPriceInWeiFieldNumber = 4;
  const ::std::string& gaspriceinwei() const;
  void set_gaspriceinwei(const ::std::string& value);
  #if LANG_CXX11
  void set_gaspriceinwei(::std::string&& value);
  #endif
  void set_gaspriceinwei(const char* value);
  void set_gaspriceinwei(const char* value, size_t size);
  ::std::string* mutable_gaspriceinwei();
  ::std::string* release_gaspriceinwei();
  void set_allocated_gaspriceinwei(::std::string* gaspriceinwei);

  // string to = 5;
  void clear_to();
  static const int kToFieldNumber = 5;
  const ::std::string& to() const;
  void set_to(const ::std::string& value);
  #if LANG_CXX11
  void set_to(::std::string&& value);
  #endif
  void set_to(const char* value);
  void set_to(const char* value, size_t size);
  ::std::string* mutable_to();
  ::std::string* release_to();
  void set_allocated_to(::std::string* to);

  // string valueInWei = 6;
  void clear_valueinwei();
  static const int kValueInWeiFieldNumber = 6;
  const ::std::string& valueinwei() const;
  void set_valueinwei(const ::std::string& value);
  #if LANG_CXX11
  void set_valueinwei(::std::string&& value);
  #endif
  void set_valueinwei(const char* value);
  void set_valueinwei(const char* value, size_t size);
  ::std::string* mutable_valueinwei();
  ::std::string* release_valueinwei();
  void set_allocated_valueinwei(::std::string* valueinwei);

  // string input = 7;
  void clear_input();
  static const int kInputFieldNumber = 7;
  const ::std::string& input() const;
  void set_input(const ::std::string& value);
  #if LANG_CXX11
  void set_input(::std::string&& value);
  #endif
  void set_input(const char* value);
  void set_input(const char* value, size_t size);
  ::std::string* mutable_input();
  ::std::string* release_input();
  void set_allocated_input(::std::string* input);

  // .JUB.Proto.Common.Bip32Path path = 1;
  bool has_path() const;
  void clear_path();
  static const int kPathFieldNumber = 1;
  const ::JUB::Proto::Common::Bip32Path& path() const;
  ::JUB::Proto::Common::Bip32Path* release_path();
  ::JUB::Proto::Common::Bip32Path* mutable_path();
  void set_allocated_path(::JUB::Proto::Common::Bip32Path* path);

  // uint32 nonce = 2;
  void clear_nonce();
  static const int kNonceFieldNumber = 2;
  ::google::protobuf::uint32 nonce() const;
  void set_nonce(::google::protobuf::uint32 value);

  // uint32 gasLimit = 3;
  void clear_gaslimit();
  static const int kGasLimitFieldNumber = 3;
  ::google::protobuf::uint32 gaslimit() const;
  void set_gaslimit(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:JUB.Proto.Ethereum.TransactionETH)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr gaspriceinwei_;
  ::google::protobuf::internal::ArenaStringPtr to_;
  ::google::protobuf::internal::ArenaStringPtr valueinwei_;
  ::google::protobuf::internal::ArenaStringPtr input_;
  ::JUB::Proto::Common::Bip32Path* path_;
  ::google::protobuf::uint32 nonce_;
  ::google::protobuf::uint32 gaslimit_;
  mutable int _cached_size_;
  friend struct ::protobuf_Jub_5fEthereum_2eproto::TableStruct;
  friend void ::protobuf_Jub_5fEthereum_2eproto::InitDefaultsTransactionETHImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ContextCfgETH

// string main_path = 1;
inline void ContextCfgETH::clear_main_path() {
  main_path_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ContextCfgETH::main_path() const {
  // @@protoc_insertion_point(field_get:JUB.Proto.Ethereum.ContextCfgETH.main_path)
  return main_path_.GetNoArena();
}
inline void ContextCfgETH::set_main_path(const ::std::string& value) {
  
  main_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:JUB.Proto.Ethereum.ContextCfgETH.main_path)
}
#if LANG_CXX11
inline void ContextCfgETH::set_main_path(::std::string&& value) {
  
  main_path_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:JUB.Proto.Ethereum.ContextCfgETH.main_path)
}
#endif
inline void ContextCfgETH::set_main_path(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  main_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:JUB.Proto.Ethereum.ContextCfgETH.main_path)
}
inline void ContextCfgETH::set_main_path(const char* value, size_t size) {
  
  main_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:JUB.Proto.Ethereum.ContextCfgETH.main_path)
}
inline ::std::string* ContextCfgETH::mutable_main_path() {
  
  // @@protoc_insertion_point(field_mutable:JUB.Proto.Ethereum.ContextCfgETH.main_path)
  return main_path_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ContextCfgETH::release_main_path() {
  // @@protoc_insertion_point(field_release:JUB.Proto.Ethereum.ContextCfgETH.main_path)
  
  return main_path_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ContextCfgETH::set_allocated_main_path(::std::string* main_path) {
  if (main_path != NULL) {
    
  } else {
    
  }
  main_path_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), main_path);
  // @@protoc_insertion_point(field_set_allocated:JUB.Proto.Ethereum.ContextCfgETH.main_path)
}

// uint32 chainID = 2;
inline void ContextCfgETH::clear_chainid() {
  chainid_ = 0u;
}
inline ::google::protobuf::uint32 ContextCfgETH::chainid() const {
  // @@protoc_insertion_point(field_get:JUB.Proto.Ethereum.ContextCfgETH.chainID)
  return chainid_;
}
inline void ContextCfgETH::set_chainid(::google::protobuf::uint32 value) {
  
  chainid_ = value;
  // @@protoc_insertion_point(field_set:JUB.Proto.Ethereum.ContextCfgETH.chainID)
}

// -------------------------------------------------------------------

// Erc20Builder

// string tokenTo = 1;
inline void Erc20Builder::clear_tokento() {
  tokento_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Erc20Builder::tokento() const {
  // @@protoc_insertion_point(field_get:JUB.Proto.Ethereum.Erc20Builder.tokenTo)
  return tokento_.GetNoArena();
}
inline void Erc20Builder::set_tokento(const ::std::string& value) {
  
  tokento_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:JUB.Proto.Ethereum.Erc20Builder.tokenTo)
}
#if LANG_CXX11
inline void Erc20Builder::set_tokento(::std::string&& value) {
  
  tokento_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:JUB.Proto.Ethereum.Erc20Builder.tokenTo)
}
#endif
inline void Erc20Builder::set_tokento(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  tokento_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:JUB.Proto.Ethereum.Erc20Builder.tokenTo)
}
inline void Erc20Builder::set_tokento(const char* value, size_t size) {
  
  tokento_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:JUB.Proto.Ethereum.Erc20Builder.tokenTo)
}
inline ::std::string* Erc20Builder::mutable_tokento() {
  
  // @@protoc_insertion_point(field_mutable:JUB.Proto.Ethereum.Erc20Builder.tokenTo)
  return tokento_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Erc20Builder::release_tokento() {
  // @@protoc_insertion_point(field_release:JUB.Proto.Ethereum.Erc20Builder.tokenTo)
  
  return tokento_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Erc20Builder::set_allocated_tokento(::std::string* tokento) {
  if (tokento != NULL) {
    
  } else {
    
  }
  tokento_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), tokento);
  // @@protoc_insertion_point(field_set_allocated:JUB.Proto.Ethereum.Erc20Builder.tokenTo)
}

// string tokenValueInWei = 2;
inline void Erc20Builder::clear_tokenvalueinwei() {
  tokenvalueinwei_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Erc20Builder::tokenvalueinwei() const {
  // @@protoc_insertion_point(field_get:JUB.Proto.Ethereum.Erc20Builder.tokenValueInWei)
  return tokenvalueinwei_.GetNoArena();
}
inline void Erc20Builder::set_tokenvalueinwei(const ::std::string& value) {
  
  tokenvalueinwei_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:JUB.Proto.Ethereum.Erc20Builder.tokenValueInWei)
}
#if LANG_CXX11
inline void Erc20Builder::set_tokenvalueinwei(::std::string&& value) {
  
  tokenvalueinwei_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:JUB.Proto.Ethereum.Erc20Builder.tokenValueInWei)
}
#endif
inline void Erc20Builder::set_tokenvalueinwei(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  tokenvalueinwei_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:JUB.Proto.Ethereum.Erc20Builder.tokenValueInWei)
}
inline void Erc20Builder::set_tokenvalueinwei(const char* value, size_t size) {
  
  tokenvalueinwei_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:JUB.Proto.Ethereum.Erc20Builder.tokenValueInWei)
}
inline ::std::string* Erc20Builder::mutable_tokenvalueinwei() {
  
  // @@protoc_insertion_point(field_mutable:JUB.Proto.Ethereum.Erc20Builder.tokenValueInWei)
  return tokenvalueinwei_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Erc20Builder::release_tokenvalueinwei() {
  // @@protoc_insertion_point(field_release:JUB.Proto.Ethereum.Erc20Builder.tokenValueInWei)
  
  return tokenvalueinwei_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Erc20Builder::set_allocated_tokenvalueinwei(::std::string* tokenvalueinwei) {
  if (tokenvalueinwei != NULL) {
    
  } else {
    
  }
  tokenvalueinwei_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), tokenvalueinwei);
  // @@protoc_insertion_point(field_set_allocated:JUB.Proto.Ethereum.Erc20Builder.tokenValueInWei)
}

// -------------------------------------------------------------------

// TransactionETH

// .JUB.Proto.Common.Bip32Path path = 1;
inline bool TransactionETH::has_path() const {
  return this != internal_default_instance() && path_ != NULL;
}
inline const ::JUB::Proto::Common::Bip32Path& TransactionETH::path() const {
  const ::JUB::Proto::Common::Bip32Path* p = path_;
  // @@protoc_insertion_point(field_get:JUB.Proto.Ethereum.TransactionETH.path)
  return p != NULL ? *p : *reinterpret_cast<const ::JUB::Proto::Common::Bip32Path*>(
      &::JUB::Proto::Common::_Bip32Path_default_instance_);
}
inline ::JUB::Proto::Common::Bip32Path* TransactionETH::release_path() {
  // @@protoc_insertion_point(field_release:JUB.Proto.Ethereum.TransactionETH.path)
  
  ::JUB::Proto::Common::Bip32Path* temp = path_;
  path_ = NULL;
  return temp;
}
inline ::JUB::Proto::Common::Bip32Path* TransactionETH::mutable_path() {
  
  if (path_ == NULL) {
    path_ = new ::JUB::Proto::Common::Bip32Path;
  }
  // @@protoc_insertion_point(field_mutable:JUB.Proto.Ethereum.TransactionETH.path)
  return path_;
}
inline void TransactionETH::set_allocated_path(::JUB::Proto::Common::Bip32Path* path) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(path_);
  }
  if (path) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      path = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, path, submessage_arena);
    }
    
  } else {
    
  }
  path_ = path;
  // @@protoc_insertion_point(field_set_allocated:JUB.Proto.Ethereum.TransactionETH.path)
}

// uint32 nonce = 2;
inline void TransactionETH::clear_nonce() {
  nonce_ = 0u;
}
inline ::google::protobuf::uint32 TransactionETH::nonce() const {
  // @@protoc_insertion_point(field_get:JUB.Proto.Ethereum.TransactionETH.nonce)
  return nonce_;
}
inline void TransactionETH::set_nonce(::google::protobuf::uint32 value) {
  
  nonce_ = value;
  // @@protoc_insertion_point(field_set:JUB.Proto.Ethereum.TransactionETH.nonce)
}

// uint32 gasLimit = 3;
inline void TransactionETH::clear_gaslimit() {
  gaslimit_ = 0u;
}
inline ::google::protobuf::uint32 TransactionETH::gaslimit() const {
  // @@protoc_insertion_point(field_get:JUB.Proto.Ethereum.TransactionETH.gasLimit)
  return gaslimit_;
}
inline void TransactionETH::set_gaslimit(::google::protobuf::uint32 value) {
  
  gaslimit_ = value;
  // @@protoc_insertion_point(field_set:JUB.Proto.Ethereum.TransactionETH.gasLimit)
}

// string gasPriceInWei = 4;
inline void TransactionETH::clear_gaspriceinwei() {
  gaspriceinwei_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& TransactionETH::gaspriceinwei() const {
  // @@protoc_insertion_point(field_get:JUB.Proto.Ethereum.TransactionETH.gasPriceInWei)
  return gaspriceinwei_.GetNoArena();
}
inline void TransactionETH::set_gaspriceinwei(const ::std::string& value) {
  
  gaspriceinwei_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:JUB.Proto.Ethereum.TransactionETH.gasPriceInWei)
}
#if LANG_CXX11
inline void TransactionETH::set_gaspriceinwei(::std::string&& value) {
  
  gaspriceinwei_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:JUB.Proto.Ethereum.TransactionETH.gasPriceInWei)
}
#endif
inline void TransactionETH::set_gaspriceinwei(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  gaspriceinwei_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:JUB.Proto.Ethereum.TransactionETH.gasPriceInWei)
}
inline void TransactionETH::set_gaspriceinwei(const char* value, size_t size) {
  
  gaspriceinwei_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:JUB.Proto.Ethereum.TransactionETH.gasPriceInWei)
}
inline ::std::string* TransactionETH::mutable_gaspriceinwei() {
  
  // @@protoc_insertion_point(field_mutable:JUB.Proto.Ethereum.TransactionETH.gasPriceInWei)
  return gaspriceinwei_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TransactionETH::release_gaspriceinwei() {
  // @@protoc_insertion_point(field_release:JUB.Proto.Ethereum.TransactionETH.gasPriceInWei)
  
  return gaspriceinwei_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TransactionETH::set_allocated_gaspriceinwei(::std::string* gaspriceinwei) {
  if (gaspriceinwei != NULL) {
    
  } else {
    
  }
  gaspriceinwei_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), gaspriceinwei);
  // @@protoc_insertion_point(field_set_allocated:JUB.Proto.Ethereum.TransactionETH.gasPriceInWei)
}

// string to = 5;
inline void TransactionETH::clear_to() {
  to_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& TransactionETH::to() const {
  // @@protoc_insertion_point(field_get:JUB.Proto.Ethereum.TransactionETH.to)
  return to_.GetNoArena();
}
inline void TransactionETH::set_to(const ::std::string& value) {
  
  to_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:JUB.Proto.Ethereum.TransactionETH.to)
}
#if LANG_CXX11
inline void TransactionETH::set_to(::std::string&& value) {
  
  to_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:JUB.Proto.Ethereum.TransactionETH.to)
}
#endif
inline void TransactionETH::set_to(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  to_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:JUB.Proto.Ethereum.TransactionETH.to)
}
inline void TransactionETH::set_to(const char* value, size_t size) {
  
  to_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:JUB.Proto.Ethereum.TransactionETH.to)
}
inline ::std::string* TransactionETH::mutable_to() {
  
  // @@protoc_insertion_point(field_mutable:JUB.Proto.Ethereum.TransactionETH.to)
  return to_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TransactionETH::release_to() {
  // @@protoc_insertion_point(field_release:JUB.Proto.Ethereum.TransactionETH.to)
  
  return to_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TransactionETH::set_allocated_to(::std::string* to) {
  if (to != NULL) {
    
  } else {
    
  }
  to_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), to);
  // @@protoc_insertion_point(field_set_allocated:JUB.Proto.Ethereum.TransactionETH.to)
}

// string valueInWei = 6;
inline void TransactionETH::clear_valueinwei() {
  valueinwei_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& TransactionETH::valueinwei() const {
  // @@protoc_insertion_point(field_get:JUB.Proto.Ethereum.TransactionETH.valueInWei)
  return valueinwei_.GetNoArena();
}
inline void TransactionETH::set_valueinwei(const ::std::string& value) {
  
  valueinwei_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:JUB.Proto.Ethereum.TransactionETH.valueInWei)
}
#if LANG_CXX11
inline void TransactionETH::set_valueinwei(::std::string&& value) {
  
  valueinwei_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:JUB.Proto.Ethereum.TransactionETH.valueInWei)
}
#endif
inline void TransactionETH::set_valueinwei(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  valueinwei_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:JUB.Proto.Ethereum.TransactionETH.valueInWei)
}
inline void TransactionETH::set_valueinwei(const char* value, size_t size) {
  
  valueinwei_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:JUB.Proto.Ethereum.TransactionETH.valueInWei)
}
inline ::std::string* TransactionETH::mutable_valueinwei() {
  
  // @@protoc_insertion_point(field_mutable:JUB.Proto.Ethereum.TransactionETH.valueInWei)
  return valueinwei_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TransactionETH::release_valueinwei() {
  // @@protoc_insertion_point(field_release:JUB.Proto.Ethereum.TransactionETH.valueInWei)
  
  return valueinwei_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TransactionETH::set_allocated_valueinwei(::std::string* valueinwei) {
  if (valueinwei != NULL) {
    
  } else {
    
  }
  valueinwei_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), valueinwei);
  // @@protoc_insertion_point(field_set_allocated:JUB.Proto.Ethereum.TransactionETH.valueInWei)
}

// string input = 7;
inline void TransactionETH::clear_input() {
  input_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& TransactionETH::input() const {
  // @@protoc_insertion_point(field_get:JUB.Proto.Ethereum.TransactionETH.input)
  return input_.GetNoArena();
}
inline void TransactionETH::set_input(const ::std::string& value) {
  
  input_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:JUB.Proto.Ethereum.TransactionETH.input)
}
#if LANG_CXX11
inline void TransactionETH::set_input(::std::string&& value) {
  
  input_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:JUB.Proto.Ethereum.TransactionETH.input)
}
#endif
inline void TransactionETH::set_input(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  input_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:JUB.Proto.Ethereum.TransactionETH.input)
}
inline void TransactionETH::set_input(const char* value, size_t size) {
  
  input_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:JUB.Proto.Ethereum.TransactionETH.input)
}
inline ::std::string* TransactionETH::mutable_input() {
  
  // @@protoc_insertion_point(field_mutable:JUB.Proto.Ethereum.TransactionETH.input)
  return input_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TransactionETH::release_input() {
  // @@protoc_insertion_point(field_release:JUB.Proto.Ethereum.TransactionETH.input)
  
  return input_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TransactionETH::set_allocated_input(::std::string* input) {
  if (input != NULL) {
    
  } else {
    
  }
  input_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), input);
  // @@protoc_insertion_point(field_set_allocated:JUB.Proto.Ethereum.TransactionETH.input)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Ethereum
}  // namespace Proto
}  // namespace JUB

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::JUB::Proto::Ethereum::ENUM_PUB_FORMAT> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::JUB::Proto::Ethereum::ENUM_PUB_FORMAT>() {
  return ::JUB::Proto::Ethereum::ENUM_PUB_FORMAT_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Jub_5fEthereum_2eproto__INCLUDED
