//
//  JUBDeviceController.h
//  JuBiterSDKDemo
//
//  Created by panmin on 2020/5/6.
//  Copyright © 2020 JuBiter. All rights reserved.
//

#import "JUBDetailBaseController.h"
#import "JUBBLEDeviceScanListView.h"
#import "JUBBLEDeviceListCell.h"


NS_ASSUME_NONNULL_BEGIN


#define BUTTON_TITLE_QUERYBATTERY       @"QUERY_BATTERY"
#define BUTTON_TITLE_DEVICEINFO         @"DEVICE_INFO"
#define BUTTON_TITLE_DEVICEAPPLETS      @"DEVICE_APPLETS"
#define BUTTON_TITLE_DEVICECERT         @"DEVICE_CERT"
#define BUTTON_TITLE_DEVICE_CHANGEPIN   @"CHANGE_PIN"
//#define BUTTON_TITLE_SENDONEAPDU        @"SEND_ONE_APDU"
#define BUTTON_TITLE_DEVICE_RESET       @"RESET"
#define BUTTON_TITLE_GENERATESEED       @"GENERATE_SEED"
#define BUTTON_TITLE_IMPORTMNEMONIC12   @"IMPORT_MNEMONIC_12"
#define BUTTON_TITLE_IMPORTMNEMONIC18   @"IMPORT_MNEMONIC_18"
#define BUTTON_TITLE_IMPORTMNEMONIC24   @"IMPORT_MNEMONIC_24"
#define BUTTON_TITLE_EXPORTMNEMONIC     @"EXPORT_MNEMONIC"


typedef NS_ENUM(NSInteger, JUB_NS_ENUM_DEV_OPT) {
    QUERY_BATTERY,
    DEVICE_INFO,
    DEVICE_APPLETS,
    DEVICE_CERT,
    DEVICE_CHANGEPIN,
//    SEND_ONE_APDU,
    DEVICE_RESET,
    GENERATE_SEED,
    IMPORT_MNEMONIC12,
    IMPORT_MNEMONIC18,
    IMPORT_MNEMONIC24,
    EXPORT_MNEMONIC,
};


@interface JUBDeviceController : JUBDetailBaseController
@end

NS_ASSUME_NONNULL_END
