name: ubuntu build CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: module
      run: |
        sudo apt install libhidapi-dev
    - name: cmake
      run: cmake .
    - name: make
      run: make
    - name: Setup tmate session
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
